{% set version = '0.3.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinyace
  version: {{ version|replace("-", "_") }}

source:
  fn: shinyAce_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/shinyAce_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinyAce/shinyAce_{{ version }}.tar.gz
  sha256: fd1bbbb3b8039368e2e851ca171bb1524174db5bc4313534aaea32c34d2c73b9

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-jsonlite
    - r-shiny >=1.0.5
  run:
    - r-base
    - r-jsonlite
    - r-shiny >=1.0.5

test:
  commands:
    - $R -e "library('shinyAce')"           # [not win]
    - "\"%R%\" -e \"library('shinyAce')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=shinyAce
  license: MIT
  summary: Ace editor bindings to enable a rich text editing environment within Shiny.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
