{% set version = "0.3.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinyace
  version: {{ version|replace("-", "_") }}

source:
  fn: shinyAce_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/shinyAce_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/shinyAce/shinyAce_{{ version }}.tar.gz
  sha256: cb4704d739f38d0faa66b161c6869550684269103b88cce18a2da51dd7d70fc3

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-shiny >=0.7.0

  run:
    - r-base
    - r-shiny >=0.7.0

test:
  commands:
    - $R -e "library('shinyAce')"  # [not win]
    - "\"%R%\" -e \"library('shinyAce')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=shinyAce
  license: MIT
  summary: Ace editor bindings to enable a rich text editing environment within Shiny.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
