# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "VzqczC1hQxA/Ay5KUGsMfOm9swMGNkVJUkVXkz92qMAYuJluUldFX7rfNmhk6wWzw61adqo3PNQcrS7Jx+PFyXc+0PcZaUDX9rMLj/walRpvmfwdEgYGCsQeZ6G6Rt4U7YLYkDMYoClNp4HhEH8ZP4P7klrO8ZJtEH1+QmKcA6ybig/y/59dhpQFqTxtLXDQf8253pCdkJUGb+ERI2HdlW394Ut1ip+4f+LFXHKYSzw2mWys6T0KLn1+eCjGU9WXnFTD8M5/A84cKgbU++qjcqXFz0kbzYtXcCHot9QNHvTQo0Zuh7wU4RMnk6rThKNVWOdCBuAoM+L2I5LkdSmgfL+A/W0AANAzzeb6UpaVX1Nsro4MrRObgaL2CBwcX/fGuRlGBKee7/GfKQv1LQKVvzeRB8tGqASLIeLD799hkx7RcbggMz8a79d7hHci2wEhduA6HikUrJQJd2EUf/pAldzxmijRvSwL1CjMqEN32dp2OA5e/IiHkI9BTeGhrtYb/+LqOaCaH/sjjSz1442KLLAtud1m/HTwzp9d1EC1bao+p5Bo4wz7ff7pORBlFLaS5IIF1/ulLN0q7UsbP3FNQFu5KPvrexpnqOXpUPcZT8AidMUejFIegqodz8bvrZZT6wX8zCFUezLlaAeR+pVTnJ/mV1VbF2doOclyDW+pq6M="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
