travis:
  secure:
    BINSTAR_TOKEN: mdgXW37EyAmlfmR0PUy1hLNudegetbp4b3SWCXPf8VtVPXAl/7k//ivJtbo8Mj/s6I+k63j53FwKqmo48sDcdoWSpxQjRxJ+kk/okIeo8jQ4rwyp5nGsB0S5N6f9yqUtUPtTTOQ0ItpYQ6ZHOuw3r95vzDIvhMv1KkBsRNdpSfxR81IgAkix1LLkX1fnCcUbEPORQpzTmYcVwAlX8Q6pRPzGY3MDIx3ubie/Kcv7xEglTeW7vrzRmtFdqehySXJ66/ny/U7N5Qf4UfUPz5l/LkfpCSu7t6g6nP4KEvAEhq+ht2p4Qlhj1V3gDI4YPygkkCHY+cHA7xu38uSBVhk7laRv0i+iEuhdSPu8F8RPwsBspIOyBmknbZJboHfJFcHU8ajW/aB3CNHWIgAbTtbI0+hn9NjkL3QG4PoGuqQF8Qw5AaMg6NIPVaYPRiQLX0v4Nt1tgnna4jQ8amugf/xIM+badXicb3+9ej83IIzZzKi1U9xxCMdYZWmO1whYW4vV0V0z/h3vpxN0wLluA7MSmH8Pff4RmyUisUdfdN8EXsFjIIfF9KGbOXohcGzjpVWpv2roFUkrgyEGyike7DYU8Io3EEZPkT1cItpGLqzVpOyChAmuede27+byB3I6weaynk//LKI4F1gtB6bFGb7tw9j/wFH3Ki6/a9KsApfcS68=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
