appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: VzqczC1hQxA/Ay5KUGsMfOm9swMGNkVJUkVXkz92qMAYuJluUldFX7rfNmhk6wWzw61adqo3PNQcrS7Jx+PFyXc+0PcZaUDX9rMLj/walRpvmfwdEgYGCsQeZ6G6Rt4U7YLYkDMYoClNp4HhEH8ZP4P7klrO8ZJtEH1+QmKcA6ybig/y/59dhpQFqTxtLXDQf8253pCdkJUGb+ERI2HdlW394Ut1ip+4f+LFXHKYSzw2mWys6T0KLn1+eCjGU9WXnFTD8M5/A84cKgbU++qjcqXFz0kbzYtXcCHot9QNHvTQo0Zuh7wU4RMnk6rThKNVWOdCBuAoM+L2I5LkdSmgfL+A/W0AANAzzeb6UpaVX1Nsro4MrRObgaL2CBwcX/fGuRlGBKee7/GfKQv1LQKVvzeRB8tGqASLIeLD799hkx7RcbggMz8a79d7hHci2wEhduA6HikUrJQJd2EUf/pAldzxmijRvSwL1CjMqEN32dp2OA5e/IiHkI9BTeGhrtYb/+LqOaCaH/sjjSz1442KLLAtud1m/HTwzp9d1EC1bao+p5Bo4wz7ff7pORBlFLaS5IIF1/ulLN0q7UsbP3FNQFu5KPvrexpnqOXpUPcZT8AidMUejFIegqodz8bvrZZT6wX8zCFUezLlaAeR+pVTnJ/mV1VbF2doOclyDW+pq6M=
